import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import { signUp } from '../../services/authService';

const schema = z.object({ fullName:z.string().trim().min(2,'Enter your name'), email:z.string().email('Enter a valid email'), phone:z.string().regex(/^\d{10}$/,'Enter a valid 10 digit mobile number'), password:z.string().min(8,'Use at least 8 characters'), confirmPassword:z.string() }).refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords do not match'});
type Values=z.infer<typeof schema>;
export function RegisterPage(){const [error,setError]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();const {register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema)});const submit=handleSubmit(async ({fullName,email,phone,password})=>{setBusy(true);setError('');try{const result=await signUp(email,password,fullName,phone);if(!result)throw new Error('Authentication is not configured yet. Add Supabase settings first.');if(result.error)throw result.error;if(result.data.session)navigate('/home',{replace:true});else setError('Account created. Check your email to confirm your account, then log in.');}catch(err){setError(err instanceof Error?err.message:'Unable to create your account.');}finally{setBusy(false);}});return <div className="mx-auto max-w-md py-4 sm:py-10"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-semibold text-stone-500"><ArrowLeft size={16}/> Back to login</Link><div className="mt-5 rounded-3xl border border-stone-100 bg-white p-5 shadow-soft sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-brand-orange">THE WOLF KAAFE</p><h1 className="mt-2 text-2xl font-black">Create Your Account</h1><p className="mt-1 text-sm text-stone-500">Join The Wolf Kaafe and start ordering your favorites.</p><form onSubmit={submit} noValidate className="mt-6 space-y-3">{([['fullName','Full Name','Your full name','text'],['email','Email','you@example.com','email'],['phone','Mobile Number','10 digit mobile number','tel'],['password','Password','At least 8 characters','password'],['confirmPassword','Confirm Password','Re-enter your password','password']] as const).map(([name,label,placeholder,type])=><div key={name}><label htmlFor={name} className="mb-1.5 block text-xs font-bold">{label}</label><input id={name} type={type} placeholder={placeholder} autoComplete={name==='fullName'?'name':name==='email'?'email':name==='phone'?'tel':name==='password'?'new-password':'new-password'} {...register(name)} className="min-h-12 w-full rounded-xl border border-stone-200 px-4 text-sm outline-none focus:border-brand-orange"/>{errors[name]?.message&&<p className="mt-1 text-xs text-brand-error">{errors[name]?.message}</p>}</div>)}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-brand-error">{error}</p>}<button disabled={busy} className="min-h-12 w-full rounded-xl bg-brand-orange py-3 text-sm font-extrabold text-white disabled:opacity-60">{busy?'Creating account…':'Create Account'}</button></form><p className="mt-5 text-center text-sm text-stone-500">Already have an account? <Link to="/login" className="font-extrabold text-brand-burnt">Login</Link></p></div></div>}
