import { ArrowLeft, ArrowRight, LayoutDashboard, Utensils } from 'lucide-react';
import { Link } from 'react-router-dom';

export function RoleSelectPage() {
  return <div className="mx-auto max-w-3xl py-5 sm:py-12"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-burnt transition hover:text-brand-orange"><ArrowLeft size={16}/> Back</Link><div className="mb-8 mt-7 text-center"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-brand-orange">THE WOLF KAAFE</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Welcome to The Wolf Kaafe</h1><p className="mt-2 text-sm text-stone-500">How would you like to continue?</p></div><div className="grid gap-4 sm:grid-cols-2">
    <section className="flex flex-col rounded-3xl border border-stone-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-brand-soft hover:shadow-soft"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-pale text-brand-orange"><Utensils size={25}/></span><h2 className="mt-5 text-xl font-extrabold">Customer</h2><p className="mt-2 flex-1 text-sm leading-relaxed text-stone-500">Browse our menu, order your favorite food, and track your order.</p><Link to="/login" className="mt-6 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand-orange px-4 text-sm font-bold text-white transition hover:bg-brand-burnt">Continue as Customer <ArrowRight size={16}/></Link></section>
    <section className="flex flex-col rounded-3xl border border-stone-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-brand-soft hover:shadow-soft"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-pale text-brand-burnt"><LayoutDashboard size={25}/></span><h2 className="mt-5 text-xl font-extrabold">Owner / Admin</h2><p className="mt-2 flex-1 text-sm leading-relaxed text-stone-500">Manage your restaurant, orders, menu, customers, and business.</p><Link to="/admin/login" className="mt-6 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand-burnt px-4 text-sm font-bold text-white transition hover:bg-brand-orange">Continue as Admin <ArrowRight size={16}/></Link></section>
  </div></div>;
}
